name: buf-push
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
        with:

          input: "proto"

      - uses: bufbuild/buf-breaking-action@v1
        with:

          input: "proto"

          # The 'main' branch of the GitHub repository that defines the module.
          # Note we specify the subdir to compare against.
          against: "https://github.com/reddyprasaddakshanapu/buf-demo.git#branch=main,ref=HEAD~1,subdir=proto"
      - uses: bufbuild/buf-push-action@v1
        with:

          input: "proto"

          buf_token: db94d3a910a7447fa86143800a5c708f8dc32584b48b477da5e4eb32aac7d6d4
